sudo: false
services:
  - redis
language: ruby
cache: bundler
rvm:
  - 2.5.1
before_install:
  - gem install bundler -v 1.16.6
  - sudo add-apt-repository -y ppa:chris-lea/libsodium
  - sudo apt-get -y update
  - sudo apt-get install -y libsodium-dev
before_script:
  - cp spec/config.yml{.sample,}
